default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # reject commits to master right away
      - id: no-commit-to-branch
        args: [--branch, master]
      # check for sensitive info and large files
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      # simple file checks
      - id: check-yaml
      - id: check-json
        exclude: ^.devcontainer/
      - id: check-ast # for python syntax
      # python checks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # Do not put large files into VC
      - id: check-added-large-files
        args: ["--maxkb=10000"] # Notebooks are pretty big
      # Windows
      - id: check-case-conflict
      # Check that theres no code BEFORE docstrings
      - id: check-docstring-first

  # remove unnecessary imports
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3 # Possible releases: https://github.com/hadialqattan/pycln/tags
    hooks:
      - id: pycln
        language_version: python310
  # sort imports with black compatible settings
  - repo: https://github.com/pycqa/isort # can be configured in setup.cfg
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  # check everything is formatted as it should
  - repo: https://github.com/psf/black
    rev: 23.1.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python310
        args: [--target-version, py310]
  # flake8
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.2.1
    hooks:
      - id: flakeheaven
        name: flakeheaven
        entry: flakeheaven lint
        types: [python]
        files: ^libs
        language: python
        additional_dependencies: [
            "flake8-bugbear",
            "flake8-builtins",
            "flake8-comprehensions",
            "flake8-eradicate",
            "flake8-pytest-style",
            "pep8-naming",
            "flake8-mutable",
            "mccabe", # Complexity checking
          ]
  # run mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1 # https://github.com/python/mypy/tags
    hooks:
      - id: mypy
        args: [--strict, --allow-subclassing-any]
        additional_dependencies:
          [
            "types-python-dateutil",
            "types-pytz",
            "types-setuptools",
            "types-requests",
            "types-redis",
            types-Deprecated,
          ]
        exclude: deploy
  # Check for security issues
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        language_version: python310
        exclude: ^tests/
